Repository F4K0/placeholder-backend, pull requests merged in 2020-02, with the labels that each got.

#3 PLCH-9 - Add CircleCI config file
  .circleci/config.yml
Labels: enhancement

#4 PLCH-9 - Fix build name issue
  .circleci/config.yml
Labels: bug

#2 PLCH-6 Create new modules to organise the project
  build.gradle
  docs-internal/build.gradle
  docs/build.gradle
  placeholder-service/build.gradle
  placeholder-service/main/java/com/f4k0/placeholder/PlaceholderApplication.java
  placeholder-service/main/java/com/f4k0/placeholder/config/SecurityConfig.java
  placeholder-service/main/resources/application.properties
  placeholder-service/main/resources/db/changelog/db.changelog-master.yaml
  placeholder-service/test/java/com/f4k0/placeholder/PlaceholderApplicationTests.java
  settings.gradle
Labels: enhancement

#5 PLCH-10 Add some useful infos and links to the project
  docs-internal/getting-started.md
Labels: documentation

#6 PLCH-1 Add initial information about the Google Maps API
  docs-internal/google-maps-api.md
Labels: documentation

#7 PLCH-13 Add general and technical overview docs
  docs-internal/resources/Basic-Concept.png
  docs-internal/technical-overview.md
  docs/high-level-overview.md
Labels: documentation

#8 PLCH-12 - Remove CircleCI and add TravisCI config file
  .circleci/config.yml
  .travis.yml
Labels: enhancement

#9 PLCH-12 - Specify JDK version
  .travis.yml
Labels: bug

#11 PLCH-14 - Add SonarCloud configuration
  .travis.yml
  placeholder-service/build.gradle
Labels: enhancement

#12 PLCH-14 - Move Sonar Token to TravisCI as an environment variable
  .travis.yml
Labels: bug

#13 PLCH-15 - Setup JaCoCo with TravisCI and SonarCloud
  .travis.yml
  placeholder-service/build.gradle
Labels: enhancement

#15 PLCH-14 - Don't run sonarqube analysis on PR opening
  .travis.yml
Labels: bug

#14 PLCH-16 - Collect information about the CI/CD pipeline setup process
  docs-internal/ci-cd-pipeline.md
Labels: documentation

#16 PLCH-21 Add the first iteration of the database design
  docs-internal/database-design.md
  docs-internal/resources/Database-Design.png
Labels: documentation

#17 PLCH-38 - Create an in-memory H2 database with R2DBC driver
  build.gradle
  placeholder-service/build.gradle
  placeholder-service/main/resources/application-windev.properties
Labels: enhancement
